"""initial_app_settings

Revision ID: cffd6db0358c
Revises: 
Create Date: 2026-04-16 21:06:19.218143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cffd6db0358c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('current_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_account_id', sa.Uuid(), nullable=True),
    sa.Column('telegram_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('notion_sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
